server:
  host: 127.0.0.1
  port: 5173

storage:
  db_path: "~/.context-cache/cc.db"
  use_faiss: true

embeddings:
  model: "intfloat/e5-small-v2"
  rerank_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  rerank_enabled: true

retrieval:
  top_k_dense: 100
  top_k_final: 8
  mmr_lambda: 0.5

watch:
  include_glob: "**/*.{md,txt,pdf,docx,eml,mbox}"
  exclude_glob: "**/{.git,.obsidian,node_modules}/**"
  poll_interval_ms: 800

privacy:
  telemetry: false
  redact_pii_by_default: false
